### ISSUE TITLE
Documentation: The used variable names do not match the shield Pins

### ISSUE THREAD

**Issue by katzlbt** [pololu/dual-mc33926-motor-shield#8]
The used variable names do not match the shield Pins! In the software you write 

//Pin map
  _nD2 = 4;
  _M1DIR = 7;
  _M1PWM = 9;
  _M2DIR = 8;
  _M2PWM = 10;
  _nSF = 12;
  _M1FB = A0;
  _M2FB = A1;

The board has:
... **no pins labeled DIR** - what is _M2DIR connected to?
... **a pin labeled PWM/NOT-D2**, but here we have a _nD2 and a _M2PWM as separate pins! What are they connected to?

This sketch is pretty useless without wiring or at least photo :-(
**Could you improve the README with a PIN-map that matches the product?**
 
I guess it refers to: https://www.pololu.com/product/1213/pictures

![MC33926](https://user-images.githubusercontent.com/260347/127288641-9004fd3b-b364-4e99-9ad0-d3562937bce9.jpeg)

**Comment by katzlbt** [comment]
Oh. There are 2 boards with the same name and same chip :-(

**Comment by ryantm** [comment]
Yes, this project is for the [Pololu Dual MC33926 Motor Driver Shield for Arduino](https://www.pololu.com/product/2503) which plugs directly into a standard Arduino and has AND gates onboard that simplify I/O requirements.

It sounds like you have the [Dual MC33926 Motor Driver Carrier](https://www.pololu.com/product/1213), so you'll have to refer to that product page for how to connect it, and write your own code for it. We do not have an Arduino library for it.
